name: Failure Test Labeled

on:
  pull_request:
    types: [labeled]


jobs:
  generate_integration_tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:error')
    name: make it fail
    steps:
      - uses: actions/checkout@v2
      - name: dump github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: fail command
        run: exit 55
      - name: error trapping
        if: ${{ failure() }}
        env:
          REPO: ${{ github.repository}}
          WORKFLOW: ${{ github.workflow }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ID: ${{ github.run_id }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FLAG_LABEL: ci:bot_issue
          PR_NUMBER: ${{ github.event.number }}
          PR_LINK: ${{github.event.pull_request._links.html.href}}
        run: |
          pip3 install PyGithub
          python3 scripts/pr_issue_on_error.py

